import type { Project } from '../types'

/**
 * Project register, from the Revised CV (08/08/2026).
 *
 * ⚠ Every `stage` must be verified with Faisal before launch. The stage is the
 * credibility anchor of this site — a project listed as "Approved" that is
 * actually at feasibility will be caught by any serious counterparty.
 *
 * Set `confidential: true` where an NDA or a live negotiation prevents naming
 * the client; the UI then renders "Confidential sponsor" automatically.
 *
 * `capacityMW` is MWac throughout, matching the CV.
 */
export const projects: Project[] = [
  {
    slug: 'eleris-1gw-solar-bess',
    title: 'Grid-tied solar + 20% BESS',
    summary:
      'One gigawatt of grid-tied solar with 20 percent battery storage for a US sponsor — technical due diligence, portfolio assessment against Power Development Board qualification policy, and tariff negotiation support.',
    capacityMW: 1000,
    technology: ['Solar PV', 'BESS'],
    stage: 'Development',
    client: 'Eleris Energy Global LLC — a concern of Pacific Group, USA',
    confidential: false,
    location: 'Bangladesh',
    role: 'Independent Consultant',
    year: 2024,
    metrics: ['1,000 MWac', '20% BESS', 'Gold Standard registered'],
    cover: null,
    featured: true,
    order: 1,
    body: '',
  },
  {
    slug: 'sumitomo-100mw-solar-bess',
    title: 'Grid-tied solar + 20% BESS',
    summary:
      'Solar with storage for a consortium led by a Japanese trading house — techno-commercial due diligence, client assessment against authority qualification policy, and proposal preparation to Power Division guideline.',
    capacityMW: 100,
    technology: ['Solar PV', 'BESS'],
    stage: 'Development',
    client: 'Consortium of Sumitomo Corporation and East Coast Group',
    confidential: false,
    location: 'Bangladesh',
    role: 'Independent Consultant',
    year: 2024,
    metrics: ['100 MWac', '20% BESS', 'Japanese sponsor'],
    cover: null,
    featured: true,
    order: 2,
    body: '',
  },
  {
    slug: 'nepcs-bmstar-100mw-solar',
    title: 'Solar power plant — government approved',
    summary: 'A 100 MW solar plant carried through to government approval as part of a joint venture.',
    capacityMW: 100,
    technology: ['Solar PV'],
    stage: 'Approved',
    client: 'JV — NEPCS and BMSTAR',
    confidential: false,
    location: 'Bangladesh',
    role: 'Director, Renewable Energy Sector',
    year: 2024,
    metrics: ['100 MW', 'Approved by government'],
    cover: null,
    featured: true,
    order: 3,
    body: '',
  },
  {
    slug: 'feemac-400mw-ppp-solar',
    title: 'Solar power plant under PPP guideline',
    summary: 'A 400 MW solar project routed through the Public-Private Partnership framework, at inception stage.',
    capacityMW: 400,
    technology: ['Solar PV'],
    stage: 'Feasibility',
    client: 'Feemac Solar Limited',
    confidential: false,
    location: 'Bangladesh',
    role: 'Director, Renewable Energy Sector',
    year: 2025,
    metrics: ['400 MW', 'PPP route', 'Inception stage'],
    cover: null,
    featured: false,
    order: 4,
    body: '',
  },
  {
    slug: 'rangunia-55mw-solar',
    title: 'Rangunia solar power plant',
    summary:
      'Led financial close and EPC supervision for a 55 MWac plant in Chittagong — the operating financial model, land acquisition, transmission line, river protection design, and the SPC board reporting framework.',
    capacityMW: 55,
    technology: ['Solar PV'],
    stage: 'Construction',
    client: 'Consortium of Metito, Aljomaih and Jinko Solar',
    confidential: false,
    location: 'Rangunia, Chittagong, Bangladesh',
    role: 'Project Manager & Local Representative',
    year: 2020,
    metrics: ['55 MWac', 'Financial close led', 'EPC supervised'],
    cover: null,
    featured: true,
    order: 5,
    body: '',
  },
  {
    slug: 'reliance-750mw-rlng-ccpp',
    title: 'RLNG-fired combined cycle, Narayanganj',
    summary:
      'Local coordination for a 750 MWac regasified-LNG combined cycle plant — liaison with BPDB, PGCB, Petrobangla, Titas, GTCL and the Power and Energy Divisions, plus PPA, IA, GSA and LLA negotiation support.',
    capacityMW: 750,
    technology: ['Gas / CCPP', 'LNG & FSRU'],
    stage: 'Development',
    client: 'Reliance Bangladesh LNG & Power Limited',
    confidential: false,
    location: 'Narayanganj, Dhaka, Bangladesh',
    role: 'Assistant Manager — LNG & FSRU',
    year: 2017,
    metrics: ['750 MWac', 'RLNG fired', 'PPA / IA / GSA'],
    cover: null,
    featured: false,
    order: 6,
    body: '',
  },
  {
    slug: 'kutubdia-lng-terminal',
    title: 'LNG terminal, Kutubdia Island',
    summary: 'A 500 mmscfd FSRU-based LNG receiving terminal — local coordination and government liaison.',
    capacityMW: null,
    technology: ['LNG & FSRU'],
    stage: 'Development',
    client: 'Reliance Bangladesh LNG & Power Limited',
    confidential: false,
    location: "Kutubdia Island, Cox's Bazar, Bangladesh",
    role: 'Assistant Manager — LNG & FSRU',
    year: 2017,
    metrics: ['500 mmscfd', 'FSRU based'],
    cover: null,
    featured: false,
    order: 7,
    body: '',
  },
  {
    slug: 'ccpp-lng-terminal-3600mw',
    title: 'CCPP and LNG import terminal',
    summary: 'Combined cycle generation paired with an LNG import terminal, taken through feasibility.',
    capacityMW: 3600,
    technology: ['Gas / CCPP', 'LNG & FSRU'],
    stage: 'Feasibility',
    client: null,
    confidential: true,
    location: 'Bangladesh',
    role: 'Manager, Operations',
    year: 2019,
    metrics: ['3,600 MW', 'LNG import terminal'],
    cover: null,
    featured: false,
    order: 8,
    body: '',
  },
  {
    slug: 'chandpur-2000mw-solar',
    title: 'Phased solar development, Chandpur',
    summary: 'A two-gigawatt solar programme structured in phases.',
    capacityMW: 2000,
    technology: ['Solar PV'],
    stage: 'Feasibility',
    client: null,
    confidential: true,
    location: 'Chandpur, Bangladesh',
    role: 'Manager, Operations',
    year: 2019,
    metrics: ['2,000 MWac', 'Phased'],
    cover: null,
    featured: false,
    order: 9,
    body: '',
  },
  {
    slug: 'solen-101mw-solar-bess',
    title: 'Grid-tied solar + 15% BESS',
    summary: 'Solar plus storage development for an independent power producer.',
    capacityMW: 101,
    technology: ['Solar PV', 'BESS'],
    stage: 'Development',
    client: 'Solen Energy Limited',
    confidential: false,
    location: 'Bangladesh',
    role: 'Independent Consultant',
    year: 2023,
    metrics: ['101 MW', '15% BESS'],
    cover: null,
    featured: false,
    order: 10,
    body: '',
  },
  {
    slug: 'hosaf-200mw-solar',
    title: '2 × 100 MW grid-tied solar',
    summary: 'Two 100 MW grid-tied PV plants developed for a domestic industrial group.',
    capacityMW: 200,
    technology: ['Solar PV'],
    stage: 'Development',
    client: 'Hosaf Group',
    confidential: false,
    location: 'Bangladesh',
    role: 'Independent Consultant',
    year: 2023,
    metrics: ['2 × 100 MW'],
    cover: null,
    featured: false,
    order: 11,
    body: '',
  },
  {
    slug: 'vapus-novelty-50mw-solar-bess',
    title: 'Grid-tied solar + 20% BESS',
    summary: 'A 50 MW grid-tied PV plant with battery storage.',
    capacityMW: 50,
    technology: ['Solar PV', 'BESS'],
    stage: 'Development',
    client: 'JV — Vapus and Novelty',
    confidential: false,
    location: 'Bangladesh',
    role: 'Independent Consultant',
    year: 2023,
    metrics: ['50 MW', '20% BESS'],
    cover: null,
    featured: false,
    order: 12,
    body: '',
  },
  {
    slug: 'patuakhali-1320mw-usc-coal',
    title: 'USC coal-fired power plant, Patuakhali',
    summary: 'Pre-feasibility study and initial environmental examination for an ultra-supercritical plant.',
    capacityMW: 1320,
    technology: ['Coal'],
    stage: 'Feasibility',
    client: 'NWPGCL',
    confidential: false,
    location: 'Patuakhali, Bangladesh',
    role: 'Electrical Engineer',
    year: 2014,
    metrics: ['1,320 MW', 'Pre-FS and IEE'],
    cover: null,
    featured: false,
    order: 13,
    body: '',
  },
  {
    slug: 'chittagong-1320mw-coal',
    title: 'Coal-fired thermal power plant, Chittagong',
    summary: 'Feasibility study and environmental impact assessment for an IPP led by a Korean EPC.',
    capacityMW: 1320,
    technology: ['Coal'],
    stage: 'Feasibility',
    client: 'IPP — POSCO E&C, Korea',
    confidential: false,
    location: 'Chittagong, Bangladesh',
    role: 'Electrical Engineer',
    year: 2016,
    metrics: ['1,320 MW', 'FS and EIA'],
    cover: null,
    featured: false,
    order: 14,
    body: '',
  },
  {
    slug: 'gazaria-350mw-coal',
    title: 'Coal-fired thermal power plant, Gazaria',
    summary: 'Detailed feasibility study with IEE, EIA and social impact assessment.',
    capacityMW: 350,
    technology: ['Coal'],
    stage: 'Feasibility',
    client: 'RPCL',
    confidential: false,
    location: 'Munshiganj, Bangladesh',
    role: 'Electrical Engineer',
    year: 2016,
    metrics: ['350 MW (+10%)', 'FS · IEE · EIA · SIA'],
    cover: null,
    featured: false,
    order: 15,
    body: '',
  },
  {
    slug: 'ghorashal-365mw-ccpp-oe',
    title: "Owner's engineer — Ghorashal CCPP",
    summary: "Document control on owner's engineering services for a 365 MW combined cycle project.",
    capacityMW: 365,
    technology: ['Gas / CCPP'],
    stage: 'Construction',
    client: 'BPDB',
    confidential: false,
    location: 'Ghorashal, Bangladesh',
    role: 'Document Controller',
    year: 2014,
    metrics: ['365 MW', "Owner's engineer"],
    cover: null,
    featured: false,
    order: 16,
    body: '',
  },
  {
    slug: 'bibiyana-south-400mw-ccpp-oe',
    title: "Owner's engineer — Bibiyana South CCPP",
    summary: "Document control on owner's engineering services for a 400 MW combined cycle project.",
    capacityMW: 400,
    technology: ['Gas / CCPP'],
    stage: 'Construction',
    client: 'BPDB',
    confidential: false,
    location: 'Bibiyana, Bangladesh',
    role: 'Document Controller',
    year: 2014,
    metrics: ['400 MW (+10%)', "Owner's engineer"],
    cover: null,
    featured: false,
    order: 17,
    body: '',
  },
  {
    slug: 'tetulia-96mw-solar',
    title: 'Grid-tied solar plant, Tetulia',
    summary:
      'Early-stage development and construction supervision for a 9.6 MWac plant — investor due diligence, RFPs, EPC offer evaluation, and ESG and EHS compliance reporting.',
    capacityMW: 9.6,
    technology: ['Solar PV'],
    stage: 'Operational',
    client: 'Symbior Solar Bangladesh Limited',
    confidential: false,
    location: 'Tetulia, Panchagarh, Bangladesh',
    role: 'Renewable Energy Consultant',
    year: 2018,
    metrics: ['9.6 MWac', 'Commissioned'],
    cover: null,
    featured: false,
    order: 18,
    body: '',
  },
  {
    slug: 'keraniganj-waste-to-energy',
    title: 'Waste-to-energy plant, Keraniganj',
    summary: 'Development of a 1–1.5 MW waste-to-energy facility.',
    capacityMW: 1.5,
    technology: ['Waste-to-Energy'],
    stage: 'Feasibility',
    client: null,
    confidential: true,
    location: 'Keraniganj, Bangladesh',
    role: 'Manager, Operations',
    year: 2019,
    metrics: ['1–1.5 MW', 'Waste to energy'],
    cover: null,
    featured: false,
    order: 19,
    body: '',
  },
  {
    slug: 'payra-gopalganj-400kv',
    title: '400 kV Payra–Gopalganj–Aminbazar transmission',
    summary: 'Open tender participation for a high-voltage transmission corridor.',
    capacityMW: null,
    technology: ['Transmission'],
    stage: 'Bidding',
    client: null,
    confidential: true,
    location: 'Bangladesh',
    role: 'Manager, Operations',
    year: 2019,
    metrics: ['400 kV', 'Open tender'],
    cover: null,
    featured: false,
    order: 20,
    body: '',
  },
  {
    slug: 'chandpur-230kv-transmission',
    title: '230 kV transmission line infrastructure, Chandpur',
    summary: 'Open tender participation for transmission infrastructure.',
    capacityMW: null,
    technology: ['Transmission'],
    stage: 'Bidding',
    client: null,
    confidential: true,
    location: 'Chandpur, Bangladesh',
    role: 'Manager, Operations',
    year: 2019,
    metrics: ['230 kV', 'Open tender'],
    cover: null,
    featured: false,
    order: 21,
    body: '',
  },
]
