import type { Project } from '../types'

/**
 * Project register, drawn from Abdullah Faisal's CV.
 *
 * ⚠ Every `stage` value must be verified with Faisal before launch. The stage is
 * the credibility anchor of this site — a project listed as "Approved" that is
 * actually at feasibility will be caught by any serious counterparty.
 *
 * Set `confidential: true` where an NDA or a live negotiation prevents naming
 * the client; the UI then renders "Confidential sponsor" automatically.
 */
export const projects: Project[] = [
  {
    slug: 'eleris-1gw-solar-bess',
    title: 'Grid-tied solar + 20% BESS',
    summary: 'One gigawatt of grid-tied solar with 20 percent battery storage, developed for a US sponsor.',
    capacityMW: 1000,
    technology: ['Solar PV', 'BESS'],
    stage: 'Development',
    client: 'Eleris Energy Global LLC — Pacific Group, USA',
    confidential: false,
    location: 'Bangladesh',
    role: 'Independent Consultant',
    year: 2023,
    metrics: ['1 GW capacity', '20% BESS', 'US sponsor'],
    cover: null,
    featured: true,
    order: 1,
    body: '',
  },
  {
    slug: 'ccpp-lng-terminal-3600mw',
    title: 'CCPP and LNG import terminal',
    summary: 'Combined cycle generation paired with an LNG import terminal, taken through feasibility.',
    capacityMW: 3600,
    technology: ['Gas / CCPP', 'LNG & FSRU'],
    stage: 'Feasibility',
    client: null,
    confidential: true,
    location: 'Bangladesh',
    role: 'Manager (Operations)',
    year: 2019,
    metrics: ['3,600 MW', 'LNG import terminal'],
    cover: null,
    featured: true,
    order: 2,
  body: '',
  },
  {
    slug: 'feemac-400mw-ppp-solar',
    title: 'Solar power plant under PPP guideline',
    summary: 'A 400 MW solar project routed through the Public-Private Partnership framework.',
    capacityMW: 400,
    technology: ['Solar PV'],
    stage: 'Feasibility',
    client: 'Feemac Solar Limited',
    confidential: false,
    location: 'Bangladesh',
    role: 'Director, Renewable Energy',
    year: 2025,
    metrics: ['400 MW', 'PPP route', 'Inception stage'],
    cover: null,
    featured: false,
    order: 3,
    body: '',
  },
  {
    slug: 'nepcs-bmstar-100mw-solar',
    title: 'Solar power plant — government approved',
    summary: 'A 100 MW solar plant carried to government approval as part of a joint venture.',
    capacityMW: 100,
    technology: ['Solar PV'],
    stage: 'Approved',
    client: 'JV — NEPCS and BMSTAR',
    confidential: false,
    location: 'Bangladesh',
    role: 'Director, Renewable Energy',
    year: 2024,
    metrics: ['100 MW', 'Government approved'],
    cover: null,
    featured: true,
    order: 4,
    body: '',
  },
  {
    slug: 'sumitomo-100mw-solar-bess',
    title: 'Grid-tied solar + 20% BESS',
    summary: 'Solar with storage developed for a consortium led by a Japanese trading house.',
    capacityMW: 100,
    technology: ['Solar PV', 'BESS'],
    stage: 'Development',
    client: 'Sumitomo Corporation and East Coast Group',
    confidential: false,
    location: 'Bangladesh',
    role: 'Independent Consultant',
    year: 2023,
    metrics: ['100 MW', '20% BESS', 'Japanese sponsor'],
    cover: null,
    featured: false,
    order: 5,
    body: '',
  },
  {
    slug: 'reliance-750mw-rlng-ccpp',
    title: 'RLNG-fired combined cycle, Narayanganj',
    summary: 'Regasified LNG combined cycle plant developed under Reliance Power.',
    capacityMW: 750,
    technology: ['Gas / CCPP', 'LNG & FSRU'],
    stage: 'Development',
    client: 'Reliance Bangladesh LNG & Power Limited',
    confidential: false,
    location: 'Narayanganj, Bangladesh',
    role: 'Assistant Manager — LNG & FSRU',
    year: 2017,
    metrics: ['750 MW', 'RLNG fired'],
    cover: null,
    featured: false,
    order: 6,
    body: '',
  },
  {
    slug: 'rangunia-55mw-solar',
    title: 'Rangunia solar power plant',
    summary: 'Managed delivery and local representation for a 55 MW solar plant in Chittagong.',
    capacityMW: 55,
    technology: ['Solar PV'],
    stage: 'Approved',
    client: 'Rangunia Solar Limited',
    confidential: false,
    location: 'Rangunia, Chittagong, Bangladesh',
    role: 'Project Manager & Local Representative',
    year: 2020,
    metrics: ['55 MW', 'Project managed'],
    cover: null,
    featured: false,
    order: 7,
    body: '',
  },
  {
    slug: 'patuakhali-1320mw-usc-coal',
    title: 'USC coal-fired power plant, Patuakhali',
    summary: 'Pre-feasibility study and initial environmental examination for an ultra-supercritical plant.',
    capacityMW: 1320,
    technology: ['Coal'],
    stage: 'Feasibility',
    client: 'NWPGCL',
    confidential: false,
    location: 'Patuakhali, Bangladesh',
    role: 'Electrical Engineer',
    year: 2014,
    metrics: ['1,320 MW', 'Pre-FS and IEE'],
    cover: null,
    featured: false,
    order: 8,
    body: '',
  },
  {
    slug: 'solen-101mw-solar-bess',
    title: 'Grid-tied solar + 15% BESS',
    summary: 'Solar plus storage development for an independent power producer.',
    capacityMW: 101,
    technology: ['Solar PV', 'BESS'],
    stage: 'Development',
    client: 'Solen Energy Limited',
    confidential: false,
    location: 'Bangladesh',
    role: 'Independent Consultant',
    year: 2023,
    metrics: ['101 MW', '15% BESS'],
    cover: null,
    featured: false,
    order: 9,
    body: '',
  },
  {
    slug: 'chandpur-2000mw-solar',
    title: 'Phased solar development, Chandpur',
    summary: 'A two gigawatt solar programme structured in phases.',
    capacityMW: 2000,
    technology: ['Solar PV'],
    stage: 'Feasibility',
    client: null,
    confidential: true,
    location: 'Chandpur, Bangladesh',
    role: 'Manager (Operations)',
    year: 2019,
    metrics: ['2,000 MW', 'Phased'],
    cover: null,
    featured: false,
    order: 10,
    body: '',
  },
  {
    slug: 'kutubdia-lng-terminal',
    title: 'LNG terminal, Kutubdia Island',
    summary: 'A 500 mmscfd LNG receiving terminal developed under Reliance Power.',
    capacityMW: null,
    technology: ['LNG & FSRU'],
    stage: 'Development',
    client: 'Reliance Bangladesh LNG & Power Limited',
    confidential: false,
    location: "Kutubdia Island, Cox's Bazar, Bangladesh",
    role: 'Assistant Manager — LNG & FSRU',
    year: 2017,
    metrics: ['500 mmscfd', 'FSRU based'],
    cover: null,
    featured: false,
    order: 11,
    body: '',
  },
  {
    slug: 'payra-gopalganj-400kv',
    title: '400 kV Payra–Gopalganj–Aminbazar transmission',
    summary: 'Open tender participation for a high-voltage transmission corridor.',
    capacityMW: null,
    technology: ['Transmission'],
    stage: 'Bidding',
    client: null,
    confidential: true,
    location: 'Bangladesh',
    role: 'Manager (Operations)',
    year: 2019,
    metrics: ['400 kV', 'Open tender'],
    cover: null,
    featured: false,
    order: 12,
    body: '',
  },
]
